"""Functions are written after tests failed, so they pass"""


def add(a, b):
    return a + b


def display_message():
    return "Message works!"
